module.exports = {
  env: {
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_SECRET,
    CONTENTFUL_DELIVERY_SECRET: process.env.CONTENTFUL_CONTENT_DELIVERY_SECRET,
    CONTENTFUL_PREVIEW_SECRET: process.env.CONTENTFUL_CONTENT_PREVIEW_SECRET,
    CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
  },
};
