module.exports = {
  env: {
    CONTENTFUL_DELIVERY_SECRET: process.env.CONTENTFUL_CONTENT_DELIVERY_SECRET,
    CONTENTFUL_PREVIEW_SECRET: process.env.CONTENTFUL_CONTENT_DELIVERY_SECRET,
    CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
    EMAIL_ADDRESS: process.env.EMAIL_ADDRESS,
    EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
    EMAIL_HOST: process.env.EMAIL_HOST,
    EMAIL_PORT: process.env.EMAIL_PORT,
    MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
    MAILCHIMP_SERVER_PREFIX: process.env.MAILCHIMP_SERVER_PREFIX,
    MAILCHIMP_LIST_ID: process.env.MAILCHIMP_LIST_ID,
    MAPBOX_API_KEY: process.env.MAPBOX_API_KEY,
  },
};
